spring.application.name=quiz
# Name der Datenbank-Datei (wird im Projektordner erstellt)
spring.datasource.url=jdbc:h2:file:./data/quizdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Erstellt/Aktualisiert die Tabellen automatisch beim Start
spring.jpa.hibernate.ddl-auto=update

# H2-Konsole aktivieren (damit du die Daten im Browser prüfen kannst)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console